### ISSUE TITLE
Simplify instructions for Docker for Windows

### ISSUE THREAD

**Issue by irobins** [OpenLiberty/draft-guide-kubernetes#25]
When using Docker for Windows, Kubernetes is now built-in and does not require explicit installation of minikube and kubectl. The instructions generally need to talk about "kubernetes" rather than "minikube", getting explicit only for how the pre-reqs are installed and started. Beyond that, kube is kube.

**Comment by yeekangc** [comment]
Using Docker for Windows and Docker for Mac that include Kubernetes will simplify the setup procedure and experience.  They work and we have merged the PR submitted.

Then, Linux or Unix will still need to follow a different path since "Kubernetes" is still separate and there are differences in the commands covered in the guide between the platforms too.  We are looking at how to best present/cover these.
