### ISSUE TITLE
Content review

### ISSUE THREAD

**Issue by evelinec** [OpenLiberty/draft-guide-kubernetes#9]
Abstract:

- [x] I think the "kubectl" command isn't needed. If you really think it's needed, it needs to be backticked?

What you'll learn

- [x] The two microservices you will deploy are called name and ping and are provided for you in the start directory. => I think it's not necessary to point to the `start` directory in this intro section. 

- [ ] It feels like explanation is needed for "Pods" and "Ingress controller" as of what they are. Looks like "Pod" is explained in the later section.

What is Kubernetes?

- [x] Can be helpful to include a link to read more about "Ingress". 

Others: 

- [x] The link in this step has an extra `\` on the test site: `kubernetes-helm, a package manager for Kubernetes called Helm. For installation instructions, see https://docs.helm.sh/using_helm/\#installing-helm.`

- [x] ...check out the `Docker guide`,.. => perhaps want to use the docker guide title here. 

- [x] ...then check the Maven build log for any potential errors and make sure that your Docker CLI is configured to use Minikube’s Docker daemon and not your host’s as described in `[Starting and preparing your cluster for Deployment]`. => the link to the `Starting and preparing your cluster for Deployment` section is enclosed within the `[]`. Is the `[]` really needed? 

- [x] Then, for the the ping microservice: => get rid off the second "the"

- [x] If you need to use additional parameters or if you would like more information on the existing parameters, visit the official IBM chart `GitHub repository`. => I think "IBM chart `GitHub repository`" is to be read together, right? ie, the link to be applied to them together, instead of just the "GitHub repository". In general, to make this clearer, ie, perhaps "visit the official IBM Helm Chart in the `GitHub repository`"? I also think the link should be added to "IBM Helm Chart" as in "visit the official `IBM Helm Chart` in the GitHub repository". 

- [ ] Running the install a chart release commands gave error: `Error: Chart incompatible with Tiller v2.10.0-rc.1`. 

- [x] Both of these chart releases will create three Kubernetes resources each: a Deployment for managing Pods, a Service for defining how Pods are accessed, and an Ingress for defining how external traffic is routed to the Service. 
=> it'd be helpful to include the names of the Deployment, Service and Ingress that were created from the chart releases. This will help following the long lines of commands better too. 

- [x] To obtain the IP address of your Minikube cluster, run the minikube ip command, the IP address will be 192.168.99.100 by default. => backtick the 192.168.99.100? 

- [x] See the official Open Liberty Helm chart GitHub repository for more information on this parameter. => here you refer to the same repository again but with different name.

- [x] Installing a new chart release is done using the same the same helm install command as before. => "the same" is written twice

- [ ] VirtualBox is required when running minikube on Mac 

- [ ] Working on Mac, when running the helm install command, there's a pop to accept the incoming network connections as a security and privacy preference. Not sure whether this should be noted. 

- [ ] Use of bold words in the guide. Can leave for ID to comment on it. 

- [ ] Different styles in inserting commands and outputs, ie, unix and windows commands together in one box; command and output in one box; command only and output only. 

- [ ] Duration of guide (without optional section) seems long

**Comment by Kubik42** [comment]
**I think the "kubectl" command isn't needed. If you really think it's needed, it needs to be backticked?**

It feels like explanation is needed for "Pods" and "Ingress controller" as of what they are. Looks like "Pod" is explained in the later section.

Can be helpful to include a link to read more about "Ingress". 

**The link in this step has an extra `\` on the test site: `kubernetes-helm, a package manager for Kubernetes called Helm. For installation instructions, see https://docs.helm.sh/using_helm/\#installing-helm.`**

This was fixed already, the site just wasnt updated.

**...then check the Maven build log for any potential errors and make sure that your Docker CLI is configured to use Minikube’s Docker daemon and not your host’s as described in `[Starting and preparing your cluster for Deployment]`. => the link to the `Starting and preparing your cluster for Deployment` section is enclosed within the `[]`. Is the `[]` really needed? **

**If you need to use additional parameters or if you would like more information on the existing parameters, visit the official IBM chart `GitHub repository`. => I think "IBM chart `GitHub repository`" is to be read together, right? ie, the link to be applied to them together, instead of just the "GitHub repository". In general, to make this clearer, ie, perhaps "visit the official IBM Helm Chart in the `GitHub repository`"? I also think the link should be added to "IBM Helm Chart" as in "visit the official `IBM Helm Chart` in the GitHub repository". **

Changed to "IBM Helm chart repository"

Running the install a chart release commands gave error: `Error: Chart incompatible with Tiller v2.10.0-rc.1`. 

Both of these chart releases will create three Kubernetes resources each: a Deployment for managing Pods, a Service for defining how Pods are accessed, and an Ingress for defining how external traffic is routed to the Service. 
=> it'd be helpful to include the names of the Deployment, Service and Ingress that were created from the chart releases. This will help following the long lines of commands better too. 

**See the official Open Liberty Helm chart GitHub repository for more information on this parameter. => here you refer to the same repository again but with different name.**

Formatted the same as the other hyperlink.

**Working on Mac, when running the helm install command, there's a pop to accept the incoming network connections as a security and privacy preference. Not sure whether this should be noted.** 

I dont think so. This is the setup side of the guide, which is entirely up to the user.

**Use of bold words in the guide. Can leave for ID to comment on it.**

I think its fine. "Unique" and "non-unique" are important and need to stand out more.

**Different styles in inserting commands and outputs, ie, unix and windows commands together in one box; command and output in one box; command only and output only. **

For command and output in the same box, I find this much nicer than separating them. Perhaps we can alter the copy button on the website to copy only the command when this kind of formatting is used. Otherwise it just feels distracting having listing blocks all over the place, especially when they could have been combined.

Same argument for putting windows and unix commands in the same listing block. Its going to look too cluttered when there are listing blocks all over the place. In this case especially, if the commands are separated into two blocks, then the users might think that they both need to be executed. Putting them in one block makes it more obvious that its either or.

Duration of guide (without optional section) seems long

**Comment by evelinec** [comment]
Didn't see changes or comment for the following points: 

- [ ] I think the "kubectl" command isn't needed. If you really think it's needed, it needs to be backticked?

- [ ] Regarding the [] for a link to refer back to a section, looks like it's the way the reference is working. You have "<<>>" in your adoc, and that gets rendered into [] on github and the website. Btw, when clicking this link on the test site, it doesn't seem to do anything.

- [ ] VirtualBox is required when running minikube on Mac. I'm referring to this sentence, "If you’re on Windows and you run into issues starting Minikube in VirtualBox, try using Hyper-V instead since Hyper-V is already required to run Docker on Windows." It sounds like only Windows requires VirtualBox. I didn't have VirtualBox setup as part of the prereqs, cus it isn't clear it is needed. Util I get to this point of the guide, where the "minikube start" command failed. The sentence in quote above is the first thing after this command, but it only refers to Windows. I think it'd be good to list VirtualBox as a requirement in the prereqs section.

**Comment by evelinec** [comment]
Also to add, I've changed my Helm version from "v2.10.0-rc.1" to "v2.9.1" then I was able to install the helm chart release successfully, re "Running the install a chart release commands gave error: Error: Chart incompatible with Tiller v2.10.0-rc.1."

**Comment by Kubik42** [comment]
**I think the "kubectl" command isn't needed. If you really think it's needed, it needs to be backticked?**

I already removed `kubectl` from the description. Which one are you referring to?

**Regarding the [] for a link to refer back to a section...**

I removed the section reference altogether.

**VirtualBox is required when running minikube on Mac.**

I think its up to the user to setup Minikube. The note about Windows is something Panagiotis ran into, so I think its worth including it.

**Working on Mac, when running the helm install command**

I dont think it should be noted then. Its part of the setup that the user is responsible for.

**Comment by evelinec** [comment]
@Kubik42 Here's the sentence with the "kubectl" command: Explore how to deploy microservices to Kubernetes and manage them with the kubectl Kubernetes CLI.

**Comment by evelinec** [comment]
New issues: 

- [ ] There are missing copyright header for the `ping` service client files

- [ ] The copyright year in the readme.adoc need to be updated to 2018 from 2017

**Comment by Kubik42** [comment]
@evelinec addressed in 37d0d91e3a8508e5d31d9571f434487a4e248f33

**Comment by evelinec** [comment]
Reviewed changes. Looks good
